import { useState, type FormEvent } from 'react'
import type { BedrockCredentials } from '../../lib/awsConfig'

export function BedrockSettings({
  creds,
  onSave,
  onClear,
  onClose,
}: {
  creds: BedrockCredentials | null
  onSave: (creds: BedrockCredentials) => void
  onClear: () => void
  onClose: () => void
}) {
  const [accessKeyId, setAccessKeyId] = useState(creds?.accessKeyId ?? '')
  const [secretAccessKey, setSecretAccessKey] = useState(creds?.secretAccessKey ?? '')
  const [sessionToken, setSessionToken] = useState(creds?.sessionToken ?? '')
  const [region, setRegion] = useState(creds?.region ?? 'us-east-1')

  function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (!accessKeyId || !secretAccessKey) return
    onSave({ accessKeyId, secretAccessKey, sessionToken: sessionToken || undefined, region })
    onClose()
  }

  return (
    <div className="bedrock-settings fade-in">
      <p className="bedrock-settings-note">
        Optional: paste temporary AWS credentials (e.g. from an STS session) to have the orchestrator's final
        summary generated by a real Bedrock call instead of the local template. Kept in <code>sessionStorage</code> only
        &mdash; never sent anywhere but AWS, never persisted after this tab closes. Some Bedrock endpoints reject
        cross-origin browser calls; if that happens, the run falls back to the local summary automatically.
      </p>
      <form onSubmit={handleSubmit} className="bedrock-settings-form">
        <input value={accessKeyId} onChange={(e) => setAccessKeyId(e.target.value)} placeholder="AWS Access Key ID" required />
        <input value={secretAccessKey} onChange={(e) => setSecretAccessKey(e.target.value)} placeholder="AWS Secret Access Key" type="password" required />
        <input value={sessionToken} onChange={(e) => setSessionToken(e.target.value)} placeholder="Session token (if using STS)" />
        <input value={region} onChange={(e) => setRegion(e.target.value)} placeholder="Region" />
        <div className="bedrock-settings-actions">
          <button type="submit" className="btn btn-primary btn-sm">Save</button>
          {creds && <button type="button" className="btn btn-ghost btn-sm" onClick={onClear}>Clear</button>}
          <button type="button" className="btn btn-ghost btn-sm" onClick={onClose}>Cancel</button>
        </div>
      </form>
    </div>
  )
}
