import { useRef, useState } from 'react'
import { getBedrockCredentials, setBedrockCredentials, type BedrockCredentials } from '../lib/awsConfig'
import {
  FLIGHT_AGENT_NAMES,
  runFlightOrchestration,
  type AgentEvent,
  type FlightRoute,
  type OrchestrationResult,
} from '../lib/flightOrchestrator'
import { BedrockSettings } from '../features/lab/BedrockSettings'
import { OrchestratorVisual, type AgentStatus } from '../features/lab/OrchestratorVisual'

const ROUTES: FlightRoute[] = [
  { origin: 'DFW', destination: 'SFO', date: '2026-10-14' },
  { origin: 'DFW', destination: 'JFK', date: '2026-11-02' },
  { origin: 'ORD', destination: 'SEA', date: '2026-12-05' },
]

export function LabTab() {
  const [routeIndex, setRouteIndex] = useState(0)
  const [running, setRunning] = useState(false)
  const [events, setEvents] = useState<AgentEvent[]>([])
  const [result, setResult] = useState<OrchestrationResult | null>(null)
  const [statuses, setStatuses] = useState<Record<string, AgentStatus>>({})
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [creds, setCreds] = useState<BedrockCredentials | null>(() => getBedrockCredentials())
  const logRef = useRef<HTMLDivElement>(null)

  const route = ROUTES[routeIndex]

  async function handleRun() {
    setRunning(true)
    setEvents([])
    setResult(null)
    setStatuses({ Orchestrator: 'active' })

    const res = await runFlightOrchestration(route, (event) => {
      setEvents((prev) => [...prev, event])
      setStatuses((prev) => ({
        ...prev,
        [event.agent]: event.agent === 'Orchestrator' ? 'active' : event.kind === 'error' ? 'error' : 'done',
      }))
      requestAnimationFrame(() => {
        logRef.current?.scrollTo({ top: logRef.current.scrollHeight, behavior: 'smooth' })
      })
    })

    setStatuses((prev) => ({ ...prev, Orchestrator: 'done' }))
    setResult(res)
    setRunning(false)
  }

  function saveCreds(next: BedrockCredentials) {
    setBedrockCredentials(next)
    setCreds(next)
  }

  function clearCreds() {
    setBedrockCredentials(null)
    setCreds(null)
  }

  return (
    <section className="tight">
      <div className="wrap">
      <div className="section-head fade-in">
        <div className="section-eyebrow">Lab</div>
        <h2>Multi-agent orchestration</h2>
        <p className="section-sub">
          An orchestrator agent dispatches a task to independent sub-agents and aggregates the result &mdash; running
          live in your browser, no backend server. This run simulates airline lookups; the final summary can be
          generated by real AWS Bedrock if you opt in below.
        </p>
      </div>

      <div className="lab-controls fade-in">
        <label className="lab-route-select">
          Route
          <select value={routeIndex} onChange={(e) => setRouteIndex(Number(e.target.value))} disabled={running}>
            {ROUTES.map((r, i) => (
              <option key={i} value={i}>{r.origin} &rarr; {r.destination} &middot; {r.date}</option>
            ))}
          </select>
        </label>
        <button className="btn btn-primary" onClick={handleRun} disabled={running}>
          {running ? 'Running…' : 'Run orchestration'}
        </button>
        <button className="btn btn-ghost btn-sm" onClick={() => setSettingsOpen((o) => !o)}>
          {creds ? 'Live Bedrock: on' : 'Live Bedrock: off'}
        </button>
      </div>

      {settingsOpen && (
        <BedrockSettings creds={creds} onSave={saveCreds} onClear={clearCreds} onClose={() => setSettingsOpen(false)} />
      )}

      <div className="lab-grid fade-in">
        <div className="lab-visual-frame">
          <OrchestratorVisual agentNames={FLIGHT_AGENT_NAMES} statuses={statuses} />
        </div>

        <div className="agent-log" ref={logRef}>
          {events.length === 0 && <p className="agent-log-empty">Run the orchestration to see agents communicate here.</p>}
          {events.map((e) => (
            <div key={e.id} className={`agent-log-line agent-log-line--${e.kind}`}>
              <span className="agent-log-agent">{e.agent}</span>
              <span>{e.message}</span>
            </div>
          ))}
        </div>
      </div>

      {result && (
        <div className="lab-result fade-in">
          <div className="lab-result-headline">
            Cheapest: <strong>{result.cheapest.airline}</strong> at <strong>${result.cheapest.price.toFixed(2)}</strong>
            {result.liveBedrock && <span className="live-badge">Live Bedrock</span>}
          </div>
          <p>{result.summary}</p>
          <div className="quote-grid">
            {result.quotes.map((q) => (
              <div key={q.airline} className={`quote-card${q.airline === result.cheapest.airline ? ' quote-card--best' : ''}`}>
                <div className="quote-airline">{q.airline}</div>
                <div className="quote-price">${q.price.toFixed(2)}</div>
                <div className="quote-duration">{q.durationMins} min</div>
              </div>
            ))}
          </div>
        </div>
      )}
      </div>
    </section>
  )
}
